from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import uvicorn
import os

app = FastAPI()

class StoryRequest(BaseModel):
    game_state: dict
    prompt: str

@app.post("/generate")
async def generate_story(req: StoryRequest):
    # This is where we will integrate Ollama for LLM and Coqui TTS.
    # For now, we return a mock response.
    print(f"Received request to generate story: {req.prompt}")
    
    return {
        "text": "This is a mock story generated by the local server.",
        "audio_url": None  # We will later return a path or base64 audio here
    }

@app.get("/ping")
async def ping():
    return {"status": "ok"}

if __name__ == "__main__":
    print("Starting Local Story Engine Server...")
    uvicorn.run(app, host="0.0.0.0", port=8000)
